//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageTasks.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;Initial Catalog=C:\\USERS\\USER\\DESKTOP\\MANAGETASKS\\MAN" +
            "AGETASKS\\MANAGETASKS.MDF;Integrated Security=True")]
        public string C__USERS_USER_DESKTOP_MANAGETASKS_MANAGETASKS_MANAGETASKS_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_USER_DESKTOP_MANAGETASKS_MANAGETASKS_MANAGETASKS_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;Initial Catalog=C:\\MANAGETASKS\\MANAGETASKS\\MANAGETASK" +
            "S.MDF;Integrated Security=True")]
        public string C__MANAGETASKS_MANAGETASKS_MANAGETASKS_MDFConnectionString {
            get {
                return ((string)(this["C__MANAGETASKS_MANAGETASKS_MANAGETASKS_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=|DataDirectory|\\ManageTasks.mdf;Inte" +
            "grated Security=True")]
        public string ManageTasksConnectionString {
            get {
                return ((string)(this["ManageTasksConnectionString"]));
            }
        }
    }
}
